server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/first
spring.datasource.username=postgres
spring.datasource.password=Shakti
# spring.datasource.password=ishan!1
# spring.datasource.password=Sulav_1552
# spring.datasource.password=rijan1234
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update